name: orders-test

on:
  pull_request:
    branches: 
      - master
    paths:
      - 'orders/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Copy repo code
      uses: actions/checkout@v2

      run: cd ./orders && npm i && npm run test:ci